#!/bin/bash
echo "Supabase Storage Setup"
echo "======================"
echo ""
echo "Step 1: Create bucket manually in Supabase Dashboard:"
echo "  1. Go to https://supabase.com/dashboard"
echo "  2. Select your project"
echo "  3. Go to Storage → New bucket"
echo "  4. Name: 'images'"
echo "  5. Set to Public"
echo "  6. Click Create"
echo ""
echo "Step 2: Run the upload script:"
echo "  npx tsx scripts/create-bucket-and-upload.ts"
echo ""
